PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Country (code TEXT PRIMARY KEY, name TEXT);
INSERT INTO "Country" VALUES('us','USA');
INSERT INTO "Country" VALUES('fr','France');
INSERT INTO "Country" VALUES('it','Italy');
CREATE TABLE Language (code TEXT PRIMARY KEY, name TEXT);
INSERT INTO "Language" VALUES('en_US','English (American)');
INSERT INTO "Language" VALUES('en_GB','English (Britanic)');
INSERT INTO "Language" VALUES('fr_FR','French');
CREATE TABLE MovieSub (code TEXT REFERENCES Language(code) ON DELETE CASCADE, movie_id INTEGER REFERENCES Movie(id) ON DELETE CASCADE);
INSERT INTO "MovieSub" VALUES('en_US',1);
INSERT INTO "MovieSub" VALUES('fr_FR',1);
CREATE TABLE Movie (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, title_orig TEXT, rlz_year INTEGER, length INTEGER, synopsys TEXT, format TEXT, region TEXT, serie TEXT, volume INTEGER, number_of_disks INTEGER);
INSERT INTO "Movie" VALUES(1,'Evil Dead 3 : L''armée des ténèbres','Evil Dead 3: Army of darkness',2014,120,'Pris dans une spirale infernale, Ash se retrouve transporté par des forces démoniaques dans l''Angleterre des années 1300. Là, il renconre un peuple victime des attaques de démons volants. Mais pour lui, une seule chose compte : retourner à son époque. Pour y parvenir il doit mettre la main sur la Nécronomicon, le Livre des Morts. Armée d''une tronçonneuse greffée au poignet et d''un fusil à canon scié dans l''autre, Ash se met en quête du grimoire sacré. Mais les forces de l''ombre ne vont pas tarder à déferler sur sa route…','DVD','2',NULL,1,1);
CREATE TABLE Personne (id INTEGER PRIMARY KEY AUTOINCREMENT, role TEXT, movie_id INTEGER REFERENCES Movie(id) ON DELETE CASCADE, firstname TEXT, lastname TEXT);
INSERT INTO "Personne" VALUES(1,'director',1,'Sam','Raimi');
INSERT INTO "Personne" VALUES(2,'director',1,'Ivan','Raimi');
INSERT INTO "Personne" VALUES(3,'producer',1,'Bruce','Campbell');
INSERT INTO "Personne" VALUES(4,'producer',1,'Another','Guy');
INSERT INTO "Personne" VALUES(5,'actor',1,'Bruce','Campbell');
INSERT INTO "Personne" VALUES(6,'actor',1,'Embeth','Davidtz');
CREATE TABLE MovieLang (code TEXT REFERENCES Language(code) ON DELETE CASCADE, movie_id INTEGER REFERENCES Movie(id) ON DELETE CASCADE);
INSERT INTO "MovieLang" VALUES('en_US',1);
INSERT INTO "MovieLang" VALUES('fr_FR',1);
CREATE TABLE MovieCast (id INTEGER PRIMARY KEY AUTOINCREMENT, character TEXT, actor_id INTEGER REFERENCES Personne(id) ON DELETE CASCADE, movie_id INTEGER REFERENCES Movie(id) ON DELETE CASCADE);
INSERT INTO "MovieCast" VALUES(1,'Ash',5,1);
INSERT INTO "MovieCast" VALUES(2,'His girl',6,1);
CREATE TABLE Tag (tag TEXT, movie_id INTEGER REFERENCES Movie(id) ON DELETE CASCADE, PRIMARY KEY(tag, movie_id));
INSERT INTO "Tag" VALUES('Comedy',1);
INSERT INTO "Tag" VALUES('Horor',1);
CREATE TABLE MovieCountry (code TEXT REFERENCES Country(code) ON DELETE CASCADE, movie_id INTEGER REFERENCES Movie(id) ON DELETE CASCADE);
INSERT INTO "MovieCountry" VALUES('us',1);
INSERT INTO "MovieCountry" VALUES('fr',1);
INSERT INTO "MovieCountry" VALUES('it',1);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('Movie',1);
INSERT INTO "sqlite_sequence" VALUES('Personne',6);
INSERT INTO "sqlite_sequence" VALUES('MovieCast',2);
COMMIT;
